name: call workflow02

on:
  workflow_call:
    inputs:
      name:
        type: string
        default: "john" 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: print input
        run: echo "Hello"
