name: Build image and push s3

on:
  workflow_dispatch:
    inputs:
      source_dir:
        description: 'Source Directory'
        required: true
        type: string
      tags:
        description: 'Test scenario tags'
        required: false
        default: '1.0' 
        type: string

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
    
    - name: copy to s3 and push to ecr
      env:
        IMAGE_TAG: ${{ inputs.tags }}
        AWS_USER: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_PASSWORD:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        aws s3 cp ./${{ inputs.source_dir }} s3://tnsforgithubaction2/models --recursive
        docker build -t mytestrepo:$IMAGE_TAG .
        docker login $ECR_REGISTRY/mytestrepo -u $AWS_USER -p $AWS_PASSWORD
        #aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $ECR_REGISTRY/mytestrepo
        docker tag mytestrepo:$IMAGE_TAG $ECR_REGISTRY/mytestrepo:$IMAGE_TAG 
        docker push $ECR_REGISTRY/mytestrepo:$IMAGE_TAG
      
