name: Maven Fetch version Linux

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14 |

    - name: version
      run: echo "version=`grep -iA 10 modelversion pom.xml  | grep version | sed 's/version//g' | sed 's/[<>/ ]//g'`" >> $GITHUB_OUTPUT
      id: project

    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }} 
    
    - name: Build project with Maven
      run: mvn -B clean install --file pom.xml
    - name: Package with maven
      run: mvn package
    - name: push image
      run: |
       sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       echo "LABEL version="${{ steps.project.outputs.version }} >> Dockerfile
       docker build . -t myapp
       docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/mysample777:${{ steps.project.outputs.version }} 
       docker push  ${{ secrets.DOCKER_USERNAME }}/mysample777:${{ steps.project.outputs.version }} 
