name: Maven Fetch version Linux

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Set output
      run: echo "version=`grep -iA 10 modelversion pom.xml  | grep version | sed 's/version//g' | sed 's/[<>/ ]//g'`" >> $GITHUB_OUTPUT
      id: project

    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }} 
