name: Maven Build and Publish

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17' 

    - name: Fetching version from POM.xml
      run: echo "version=`grep -iA 10 modelversion pom.xml  | grep version | sed 's/version//g' | sed 's/[<>/ ]//g'`" >> $GITHUB_OUTPUT
      id: project

    - name: Show extracted version
      run: echo ${{ steps.project.outputs.version }} 
    
    - name: Build project with Maven
      run: mvn -B clean install --file pom.xml
      
    - name: Login to DockerHub Repo
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
    - name: Insert LABEL and push image to Dockerhub
      run: |
       #sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
       echo "LABEL version="${{ steps.project.outputs.version }} >> Dockerfile
       docker build . -t myapp
       docker tag myapp:latest ${{ secrets.DOCKER_USERNAME }}/mysample777:${{ steps.project.outputs.version }} 
       docker push  ${{ secrets.DOCKER_USERNAME }}/mysample777:${{ steps.project.outputs.version }} 
