name: Maven Fetch version Linux

on: [push]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14

    - name: Set output
      run: echo "version=`grep -iA 10 modelversion pom.xml  | grep version | sed 's/version//g' | sed 's/[<>/ ]//g'`" >> $GITHUB_OUTPUT
      id: project
      
    - name: Set output
      run: echo "label = `echo LABEL = ${{ steps.project.outputs.version }}`" >> $GITHUB_OUTPUT
      id: projectlbl

    - name: Show extracted Maven project version
      run: echo ${{ steps.project.outputs.version }} 
    
    - name: Build project with Maven
      run: mvn -B clean install --file pom.xml
    - name: Package with maven
      run: mvn package
    
    - run: mkdir artifact && cp webapp/target/*.war artifact
    
    - uses: actions/upload-artifact@v2
      with:
       name: Package
       path: artifact  
    - name: Login to DockerHub Repo
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v1     
      with:       
         username: ${{ secrets.DOCKER_USERNAME }} 
         password:  ${{ secrets.DOCKER_PASSWORD }}
         repository: ${{ secrets.DOCKER_USERNAME }}/mysample777     
         tags: ${{ steps.project.outputs.version }}
         labels: ${{ steps.projectlbl.outputs.label }}
