
name: workflow_01_new_samerepo
on: 
  repository_dispatch:
    types: first-job-samerepo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Test
        run: |
          curl -X POST https://api.github.com/repos/saravanaraja2021/sample-mvn-app/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "second-job-samerepo", "client_payload": { "message": "job successful" }'
      - uses: actions/checkout@v3
