name: workflow_02
on:
  repository_dispatch:
    types: second-job-samerepo
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggering Wokflow 2"
      - name: Checkout
        uses: actions/checkout@v2
