name: workflow_test_3_parent
on: 
  repository_dispatch:
    types: workflow-test-3

jobs:
  workflow_test_3:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
     
      - name: AWS service
        run: |
          curl -X POST https://api.github.com/repos/saravanaraja2021/sample-mvn-app/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "second-job-samerepo", "client_payload": {"SNO": "1", "CLOUD": "AWS", "SERVICE" : "EC2" } }'
          sleep 5       
  
      - name: azure service
        run: |
          curl -X POST https://api.github.com/repos/saravanaraja2021/sample-mvn-app/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "second-job-samerepo", "client_payload": { "SNO": "2","CLOUD": "AZURE", "SERVICE" : "Virtual Machine" } }'
          sleep 5

      - name: GCP service
        run: |
          curl -X POST https://api.github.com/repos/saravanaraja2021/sample-mvn-app/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.ACTIONS_KEY }} \
          --data '{"event_type": "second-job-samerepo", "client_payload": { "SNO": "3","CLOUD": "GCP", "SERVICE" : "Compute Engine" } }'
